const now=Date.now();
export const seedTransactions=[
 {id:'seed-1',beneficiary:'ABC Traders',amount:5000,purpose:'Inventory',riskScore:12,riskLevel:'LOW',ruleRiskScore:10,mlAnomalyScore:.15,isAnomaly:false,riskReasons:['Consistent with payment history'],aiExplanation:'This payment matches your established pattern with ABC Traders.',paymentStatus:'completed',createdAt:new Date(now-21*864e5).toISOString()},
 {id:'seed-2',beneficiary:'ABC Traders',amount:6000,purpose:'Inventory',riskScore:16,riskLevel:'LOW',ruleRiskScore:10,mlAnomalyScore:.25,isAnomaly:false,riskReasons:['Consistent with payment history'],aiExplanation:'This payment is within your normal range.',paymentStatus:'completed',createdAt:new Date(now-14*864e5).toISOString()},
 {id:'seed-3',beneficiary:'ABC Traders',amount:5500,purpose:'Inventory',riskScore:11,riskLevel:'LOW',ruleRiskScore:8,mlAnomalyScore:.16,isAnomaly:false,riskReasons:['Consistent with payment history'],aiExplanation:'No unusual signals were detected.',paymentStatus:'completed',createdAt:new Date(now-8*864e5).toISOString()},
 {id:'seed-4',beneficiary:'ABC Traders',amount:6500,purpose:'Inventory',riskScore:18,riskLevel:'LOW',ruleRiskScore:12,mlAnomalyScore:.27,isAnomaly:false,riskReasons:['Consistent with payment history'],aiExplanation:'This amount is consistent with prior payments.',paymentStatus:'completed',createdAt:new Date(now-4*864e5).toISOString()},
 {id:'seed-5',beneficiary:'XYZ Supplies',amount:10000,purpose:'Office supplies',riskScore:14,riskLevel:'LOW',ruleRiskScore:10,mlAnomalyScore:.19,isAnomaly:false,riskReasons:['Established beneficiary'],aiExplanation:'This payment aligns with prior activity.',paymentStatus:'completed',createdAt:new Date(now-18*864e5).toISOString()},
 {id:'seed-6',beneficiary:'XYZ Supplies',amount:11000,purpose:'Office supplies',riskScore:20,riskLevel:'LOW',ruleRiskScore:14,mlAnomalyScore:.29,isAnomaly:false,riskReasons:['Established beneficiary'],aiExplanation:'No material risk indicators were found.',paymentStatus:'completed',createdAt:new Date(now-11*864e5).toISOString()},
 {id:'seed-7',beneficiary:'XYZ Supplies',amount:9500,purpose:'Office supplies',riskScore:13,riskLevel:'LOW',ruleRiskScore:9,mlAnomalyScore:.2,isAnomaly:false,riskReasons:['Established beneficiary'],aiExplanation:'This is a routine payment.',paymentStatus:'completed',createdAt:new Date(now-5*864e5).toISOString()},
 {id:'seed-8',beneficiary:'Nova Digital',amount:28000,purpose:'Campaign retainer',riskScore:57,riskLevel:'MEDIUM',ruleRiskScore:55,mlAnomalyScore:.61,isAnomaly:true,riskReasons:['First-time beneficiary','Higher than typical merchant payment'],aiExplanation:'This is a first payment to Nova Digital and its value is above your broader payment baseline.',paymentStatus:'completed',createdAt:new Date(now-2*864e5).toISOString()},
 {id:'seed-9',beneficiary:'Qubit Labs',amount:52000,purpose:'Software license',riskScore:88,riskLevel:'HIGH',ruleRiskScore:85,mlAnomalyScore:.92,isAnomaly:true,riskReasons:['Unusually large payment','ML anomaly detected'],aiExplanation:'The amount significantly differs from your usual transaction behaviour. Verify the invoice and beneficiary.',paymentStatus:'prevented',createdAt:new Date(now-1*864e5).toISOString()}
];
